// Creacion de tareas fluidas
export const FTASK_CREATED = "FTASK_CREATED"
export const FTASK_CREATED_DONE = "FTASK_CREATED_DONE"
export const FTASK_CREATED_FAILED = "FTASK_CREATED_FAILED"

//Reorganizacion
export const FTASK_POSTPONED = "FTASK_POSTPONED"
export const FTASK_POSTPONED_DONE = "FTASK_POSTPONED_DONE"
export const FTASK_POSTPONED_FAILED = "FTASK_POSTPONED_FAILED"

export const FTASK_COMPLETED = "FTASK_COMPLETED"
export const FTASK_COMPLETED_DONE = "FTASK_COMPLETED_DONE"
export const FTASK_COMPLETED_FAILED = "FTASK_COMPLETED_FAILED"

export const FTASK_ELIMINATED = "FTASK_ELIMINATED"
export const FTASK_ELIMINATED_DONE = "FTASK_ELIMINATED_DONE"
export const FTASK_ELIMINATED_FAILED = "FTASK_ELIMINATED_FAILED"


//Usuarios
export const USER_CREATED = "USER_CREATED"
export const USER_CREATED_DONE = "USER_CREATED_DONE"
export const USER_CREATED_FAILED = "USER_CREATED_FAILED"

export const USER_LOGGED = "USER_LOGGED"
export const USER_LOGGED_DONE = "USER_LOGGED_DONE"
export const USER_LOGGED_FAILED = "USER_LOGGED_FAILED"

export const USER_LOGGED_OUT = "USER_LOGGED_OUT"
export const USER_LOGGED_OUT_DONE = "USER_LOGGED_OUT_DONE"
export const USER_LOGGED_OUT_FAILED = "USER_LOGGED_OUT_FAILED"